version: '3'

services:
  postgraphql:
    image: postgraphql/postgraphql
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    links:
      - postgres
    entrypoint: "postgraphql -n 0.0.0.0 --cors"
    environment:
      #DB_DEFAULT_ROLE: postgres
      DB_GRAPHQL_PATH: "/graphql"
      DB_GRAPHIQL_PATH: "/graphiql"
      PG_SECRET: "deadbeefcafe"
      DB_SCHEMA: "public"
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: postgres
  postgres:
    build: sql/.
  webrtc:
    build: webrtc/.
    ports:
      - "8080:8080"
  web:
    depends_on:
      - postgraphql
      - webrtc
    build: .
    ports:
      - "3000:5000"
